services:
  backend:
    image: cloud-backend
    container_name: cloud-backend
    ports:
      - "3000:3000"
    depends_on:
      - db


  frontend:
    image: cloud-frontend
    container_name: cloud-frontend
    depends_on:
      - backend
    ports:
      - "8000:8000"
    environment:
      PUBLIC_API_URL: http://localhost:3000
      VITE_API_URL: http://localhost:3000


  db:
    image: postgres:alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: university_nixos
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
